### ISSUE TITLE
acsetup fails with error on Windows

### ISSUE THREAD

**Issue by ptitzler** [ibm-watson-data-lab/serverless-autocomplete#7]
```
>node bin\acsetup.js ..\auto.txt
serverlessautocomplete
Creating OpenWhisk action: auto

fs.js:1089
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\IBM_AD~1\AppData\Local\Temp\tmp-528eXZNshqEtspW\action.zip'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at Object.rm (D:\medium-tests\serverless-autocomplete\lib\file.js:45:6)
    at Object.<anonymous> (D:\medium-tests\serverless-autocomplete\bin\acsetup.js:45:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

```

**Comment by ptitzler** [comment]
* Issue 1: The ZIP file cannot be created. Reason: `file.js` relies on `zip` utility which may or may not be installed on Windows. Because the file couldn't be created the subsequent removal attempt failed.
* Issue 2: ZIP file creation failure wasn't detected.
* Issue 3: See #5
