### ISSUE TITLE
Fails on namespace discovery

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-watson-data-lab/serverless-autocomplete#8]
@glynnbird interested in using this but there seems to be a problem. 

```
/usr/local/lib/node_modules/serverless-autocomplete/lib/whisk.js:15
  return retval.trim();
                ^
TypeError: Cannot read property 'trim' of null
    at Object.namespace (/usr/local/lib/node_modules/serverless-autocomplete/lib/whisk.js:15:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless-autocomplete/bin/acsetup.js:55:29)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

**Comment by glynnbird** [comment]
It looks like the code is running the following command-line command:

```sh
$ wsk namespace list
namespaces
sue@aol.com
```

ignoring the `namespaces` string and picking the next string. If this command doesn't work on your computer, try logging in your `wsk`/`ibmcloud wsk`/`ibmcloud fn` tool 

https://console.bluemix.net/docs/openwhisk/bluemix_cli.html#cloudfunctions_cli

All of the CLI command names seem to have changed since I wrote this but `wsk namespace list` still works on my computer, as long as I'm logged in. 

Failing that, fork the project and force the `namespace` function in `lib/whisk.js` to return your CF space.

**Comment by glynnbird** [comment]
Actually scratch that. I've republished this thing to update it to `ibmcloud fn` instead of `bx wsk`. So just reinstall this package, but make sure you've got the latest CLI installed and have the `cloud-functions` plugin installed https://console.bluemix.net/docs/openwhisk/bluemix_cli.html#cloudfunctions_cli and it seems to work.

**Comment by isc-rsingh** [comment]
@glynnbird thanks yes it's working for me  now
